
#ifndef GC_MAIL_CONST_H 
#define GC_MAIL_CONST_H 

#include "game_string_assistant.h"

extern fox::CStrMap					gMailStr;//字符串索引


inline void InitString(fox::CStrMap& vrStrMap)
{

	guard;

	//将来可能读表
	vrStrMap.Str("FRIEND_NULL_MESSAGE",R(FRIEND_NULL_MESSAGE));// 好友的空字符串！
	vrStrMap.Str(FRIEND_NULL_MESSAGE,"FRIEND_NULL_MESSAGE");
	vrStrMap.Str("OBJECT_NOT_IN_REGION",R(OBJECT_NOT_IN_REGION));// 物体不在该区域！
	vrStrMap.Str(OBJECT_NOT_IN_REGION,"OBJECT_NOT_IN_REGION");
	vrStrMap.Str("OBJECT_NOT_PLAYER",R(OBJECT_NOT_PLAYER));// 该物体不是玩家，无法成为好友！
	vrStrMap.Str(OBJECT_NOT_PLAYER,"OBJECT_NOT_PLAYER");
	vrStrMap.Str("FRIEND_LIST_OVERFLOW",R(FRIEND_LIST_OVERFLOW));// 好友列表已满，无法邀请别人！
	vrStrMap.Str(FRIEND_LIST_OVERFLOW,"FRIEND_LIST_OVERFLOW");
	vrStrMap.Str("FRIEND_NOT_IN_LIST",R(FRIEND_NOT_IN_LIST));// 该好友不在列表中！
	vrStrMap.Str(FRIEND_NOT_IN_LIST,"FRIEND_NOT_IN_LIST");// FRIEND_NOT_IN_LIST


	vrStrMap.Str("OTHER_FRIEND_LIST_OVERFLOW",R(OTHER_FRIEND_LIST_OVERFLOW));// 对方好友人数已满，无法加入！
	vrStrMap.Str(OTHER_FRIEND_LIST_OVERFLOW,"OTHER_FRIEND_LIST_OVERFLOW");
	vrStrMap.Str("OTHER_ADD_SELF",R(OTHER_ADD_SELF));// [%s]成为你的好友！
	vrStrMap.Str(OTHER_ADD_SELF,"OTHER_ADD_SELF");
	vrStrMap.Str("SELF_FRIEND_LIST_OVERFLOW_OTHER_CANNOT_ADD",R(SELF_FRIEND_LIST_OVERFLOW_OTHER_CANNOT_ADD));// 当前好友列表到达上限，[%s]无法加入！
	vrStrMap.Str(SELF_FRIEND_LIST_OVERFLOW_OTHER_CANNOT_ADD,"SELF_FRIEND_LIST_OVERFLOW_OTHER_CANNOT_ADD");
	vrStrMap.Str("OTHER_BANISH_SELF",R(OTHER_BANISH_SELF));// [%s]将好友关系解除！
	vrStrMap.Str(OTHER_BANISH_SELF,"OTHER_BANISH_SELF");
	vrStrMap.Str("OBJECT_NOT_FIND",R(OBJECT_NOT_FIND));// 该物件不存在！
	vrStrMap.Str(OBJECT_NOT_FIND,"OBJECT_NOT_FIND");

    
    
    vrStrMap.Str("CHOOSE_PLAYER_ADD_FRIEND",R(CHOOSE_PLAYER_ADD_FRIEND));// 请选择要邀请的玩家。
	vrStrMap.Str(CHOOSE_PLAYER_ADD_FRIEND,"CHOOSE_PLAYER_ADD_FRIEND");
	vrStrMap.Str("SELF_CAN_NOT_ADD_SELF",R(SELF_CAN_NOT_ADD_SELF));// 自己不能成为自己的好友！
	vrStrMap.Str(SELF_CAN_NOT_ADD_SELF,"SELF_CAN_NOT_ADD_SELF");
	vrStrMap.Str("SELF_BANISH_OTHER",R(SELF_BANISH_OTHER));// [%s]已经从好友列表中删除！
	vrStrMap.Str(SELF_BANISH_OTHER,"SELF_BANISH_OTHER");
	vrStrMap.Str("OTHER_INVITE_SELF",R(OTHER_INVITE_SELF));// [%s]邀请你加入好友！
	vrStrMap.Str(OTHER_INVITE_SELF,"OTHER_INVITE_SELF");
	vrStrMap.Str("MAIL_LOCAL_NOT_THIS_DBID_NAME",R(MAIL_LOCAL_NOT_THIS_DBID_NAME));// 本地没有该玩家数据！！
	vrStrMap.Str(MAIL_LOCAL_NOT_THIS_DBID_NAME,"MAIL_LOCAL_NOT_THIS_DBID_NAME");

	vrStrMap.Str("OTHER_FRIEND_REFUSE_INVITE",R(OTHER_FRIEND_REFUSE_INVITE));// 对方拒绝成为你的好友！！
	vrStrMap.Str(OTHER_FRIEND_REFUSE_INVITE,"OTHER_FRIEND_REFUSE_INVITE");
	vrStrMap.Str("FRIEND_ALREADY_IN_LIST",R(FRIEND_ALREADY_IN_LIST));// 该玩家已经是你的好友！
	vrStrMap.Str(FRIEND_ALREADY_IN_LIST,"FRIEND_ALREADY_IN_LIST");

	vrStrMap.Str("FRIEND_WAIT_PLAYER_RESPOND",R(FRIEND_WAIT_PLAYER_RESPOND));// 等待对方回答...
	vrStrMap.Str(FRIEND_WAIT_PLAYER_RESPOND,"FRIEND_WAIT_PLAYER_RESPOND");

	vrStrMap.Str("MASTER_BANISH_YOU",R(MASTER_BANISH_YOU));//您已经被[%s]逐出师门！
	vrStrMap.Str(MASTER_BANISH_YOU,"MASTER_BANISH_YOU");
	vrStrMap.Str("PRENTICE_RUN_AWAY",R(PRENTICE_RUN_AWAY));//您的徒弟[%s]已经叛师！
	vrStrMap.Str(PRENTICE_RUN_AWAY,"PRENTICE_RUN_AWAY");


    vrStrMap.Str("MSG_MAIL_SEND_TO_NAME_NULL",R(MSG_MAIL_SEND_TO_NAME_NULL));// 收件人不能为空！
	vrStrMap.Str(MSG_MAIL_SEND_TO_NAME_NULL,"MSG_MAIL_SEND_TO_NAME_NULL");
	vrStrMap.Str("MSG_MAIL_TITLE_NULL",R(MSG_MAIL_TITLE_NULL));// 标题不能为空！
	vrStrMap.Str(MSG_MAIL_TITLE_NULL,"MSG_MAIL_TITLE_NULL");
	vrStrMap.Str("MSG_MAIL_CONTENT_NULL",R(MSG_MAIL_CONTENT_NULL));// 内容不能为空！
	vrStrMap.Str(MSG_MAIL_CONTENT_NULL,"MSG_MAIL_CONTENT_NULL");
	vrStrMap.Str("MSG_MAIL_RECEIVE_PLAYER_NOT_IN_FRIEND_LIST",R(MSG_MAIL_RECEIVE_PLAYER_NOT_IN_FRIEND_LIST));// 收信人不在好友列表中！
	vrStrMap.Str(MSG_MAIL_RECEIVE_PLAYER_NOT_IN_FRIEND_LIST,"MSG_MAIL_RECEIVE_PLAYER_NOT_IN_FRIEND_LIST");


    return;
	unguard;
}


#endif//GC_MAIL_CONST_H 