
#ifndef GC_TEAM_CONST_H
#define GC_TEAM_CONST_H

#include "game_string_assistant.h"
#include "game_team_share_const.h"

extern fox::CStrMap					gTeamStr;//字符串索引


inline void InitString()
{

	//将来可能读表
	gTeamStr.Str("TEAM_COUNT_OVER",R(TEAM_COUNT_OVER));// 队伍人数已满！
	gTeamStr.Str("NOT_TEAM_CAPTAIN",R(NOT_TEAM_CAPTAIN));// 不是队长无法使用该功能！
	gTeamStr.Str("TEAM_NOT_EXIST",R(TEAM_NOT_EXIST));// 当前没有队伍！
	gTeamStr.Str("BANISH_MEMBER",R(BANISH_MEMBER));// [%s]被驱逐出队伍了！
	gTeamStr.Str("MEMBER_NOT_EXIST",R(MEMBER_NOT_EXIST));// 该队员不存在！
	gTeamStr.Str("SELF_LEFT_TEAM",R(SELF_LEFT_TEAM));// 你离开了[%s]的队伍
	gTeamStr.Str("TEAM_DISMISS",R(TEAM_DISMISS));// 队伍被解散！
	gTeamStr.Str("MEMBER_ADD_TEAM",R(MEMBER_ADD_TEAM));// [%s]加入了队伍。
	gTeamStr.Str("REFUSE_INVITE",R(REFUSE_INVITE));// [%s]拒绝了你的组队邀请！
	gTeamStr.Str("INVITE_ADD_TEAM",R(INVITE_ADD_TEAM));// 加入[%s]的队伍么？


	gTeamStr.Str("BANISH_FROM_TEAM",R(BANISH_FROM_TEAM));// 你离开了[%s]的队伍。
	gTeamStr.Str("LEAVE_TEAM",R(LEAVE_TEAM));// [%s]离开了队伍。
	gTeamStr.Str("ALREADY_IN_TEAM",R(ALREADY_IN_TEAM));// 已经在队伍中！
	gTeamStr.Str("CHOOSE_MEMBER_ADD_TEAM",R(CHOOSE_MEMBER_ADD_TEAM));// 请选择要组队的玩家。
	gTeamStr.Str("CHOOSE_MEMBER_BANISH_FROM_TEAM",R(CHOOSE_MEMBER_BANISH_FROM_TEAM));// 请选择要驱逐的玩家。
	gTeamStr.Str("ADD_TEAM_SUCCEED",R(ADD_TEAM_SUCCEED));// 已经成功加入了[%s]的队伍！
	gTeamStr.Str("THAT_PLAY_ALREADY_ADD_OTHER_TEAM",R(THAT_PLAY_ALREADY_ADD_OTHER_TEAM));// 无法加入，那个玩家已经加入其它的队伍！
	gTeamStr.Str("NOT_MEMBER_TEAM_DISMISS",R(NOT_MEMBER_TEAM_DISMISS));// 人数不足，队伍被解散！
	gTeamStr.Str("THAT_OBJECT_NOT_PLAYER",R(THAT_OBJECT_NOT_PLAYER));// 那个物体不是玩家！
	gTeamStr.Str("THAT_PLAYER_NOT_INLINE",R(THAT_PLAYER_NOT_INLINE));// 该玩家不存在！
	
	gTeamStr.Str("TEAM_LOCAL_NOT_THIS_DBID_NAME",R(TEAM_LOCAL_NOT_THIS_DBID_NAME));// 本地没有该玩家数据！！
	gTeamStr.Str("TEAM_WAIT_PLAYER_RESPOND",R(TEAM_WAIT_PLAYER_RESPOND));// 等待对方回答...
	gTeamStr.Str("TEAM_OBJECT_NOT_IN_REGION",R(TEAM_OBJECT_NOT_IN_REGION));// 物体不在该区域！
	gTeamStr.Str("THAT_PLAYER_TEAM_OFF",R(THAT_PLAYER_TEAM_OFF));// 对方组队开关关闭
	
	


	//数字索引
	gTeamStr.Str(TEAM_COUNT_OVER,"TEAM_COUNT_OVER");
	gTeamStr.Str(NOT_TEAM_CAPTAIN,"NOT_TEAM_CAPTAIN");
	gTeamStr.Str(TEAM_NOT_EXIST,"TEAM_NOT_EXIST");
	gTeamStr.Str(BANISH_MEMBER,"BANISH_MEMBER");
	gTeamStr.Str(MEMBER_NOT_EXIST,"MEMBER_NOT_EXIST");
	gTeamStr.Str(SELF_LEFT_TEAM,"SELF_LEFT_TEAM");
	gTeamStr.Str(TEAM_DISMISS,"TEAM_DISMISS");
	gTeamStr.Str(MEMBER_ADD_TEAM,"MEMBER_ADD_TEAM");
	gTeamStr.Str(REFUSE_INVITE,"REFUSE_INVITE");
	gTeamStr.Str(INVITE_ADD_TEAM,"INVITE_ADD_TEAM");


	gTeamStr.Str(BANISH_FROM_TEAM,"BANISH_FROM_TEAM");
	gTeamStr.Str(LEAVE_TEAM,"LEAVE_TEAM");
	gTeamStr.Str(ALREADY_IN_TEAM,"ALREADY_IN_TEAM");
	gTeamStr.Str(CHOOSE_MEMBER_ADD_TEAM,"CHOOSE_MEMBER_ADD_TEAM");
	gTeamStr.Str(CHOOSE_MEMBER_BANISH_FROM_TEAM,"CHOOSE_MEMBER_BANISH_FROM_TEAM");
	gTeamStr.Str(ADD_TEAM_SUCCEED,"ADD_TEAM_SUCCEED");
	gTeamStr.Str(THAT_PLAY_ALREADY_ADD_OTHER_TEAM,"THAT_PLAY_ALREADY_ADD_OTHER_TEAM");
	gTeamStr.Str(NOT_MEMBER_TEAM_DISMISS,"NOT_MEMBER_TEAM_DISMISS");
	gTeamStr.Str(THAT_OBJECT_NOT_PLAYER	,"THAT_OBJECT_NOT_PLAYER");
	gTeamStr.Str(THAT_PLAYER_NOT_INLINE,"THAT_PLAYER_NOT_INLINE");

	gTeamStr.Str(TEAM_LOCAL_NOT_THIS_DBID_NAME,"TEAM_LOCAL_NOT_THIS_DBID_NAME");
	gTeamStr.Str(TEAM_WAIT_PLAYER_RESPOND,"TEAM_WAIT_PLAYER_RESPOND");
	gTeamStr.Str(TEAM_OBJECT_NOT_IN_REGION,"TEAM_OBJECT_NOT_IN_REGION");
	gTeamStr.Str(THAT_PLAYER_TEAM_OFF,"THAT_PLAYER_TEAM_OFF");
	
	

	

	return;
}

#endif//GC_TEAM_CONST_H
