#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <WinUser.h>
#include <assert.h>
#include <fstream>
#include <io.h>
#include <list>
#include <stdlib.h>
#include <string>
#include <string.h>
#include <vector>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
#include <ShellAPI.h>
