//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tool_scene.rc
//
#define IDR_TOOLBAR_BRUSH_MAP           4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDR_HTML_HELPDIALOGUSE          103
#define IDR_HTML_DLGNEWSCENE            104
#define IDR_MAINFRAME                   128
#define IDR_RTEngineSceneTYPE           129
#define IDC_LISTBOX_AREA                129
#define IDC_EDIT_AREA_NAME              130
#define IDC_EDIT_AREA_DATA              131
#define ID_GRIDITEM_OPTION_OBJHEIGHTLIGHT 132
#define ID_GRIDITEM_OPTION_OBJHEIGHTLIGHT_COLOR_SPE 133
#define ID_GRIDITEM_OPTION_OBJHEIGHTLIGHT_SCALE 134
#define ID_GRIDITEM_OPTION_OBJHEIGHTLIGHT_COLOR_EMI 135
#define ID_GRIDITEM_OPTION_OBJHEIGHTLIGHT_COLOR_DIF 136
#define ID_GRIDITEM_OPTION_OBJHEIGHTLIGHT_SPE_POWER 137
#define IDB_BITMAP_BRUSH_OBJECT         140
#define ID_VIEW_BRUSH_MAP               141
#define ID_VIEW_BRUSH_OBJECT            142
#define ID_VIEW_BRUSH_GRASS             143
#define ID_VIEW_BRUSH_PROPERTY          144
#define ID_VIEW_BRUSH_VERTEX            145
#define ID_VIEW_BRUSH_COLOR             146
#define ID_VIEW_AREA_LIST               147
#define ID_AREA_LIST_VIEW               148
#define IDD_DLG_BRUSH_COLOR             149
#define IDD_DLG_BRUSH_VERTEX            150
#define ID_GRIDITEM_ENVIRONMENT         151
#define ID_BRUSHMAP_OPTION              152
#define IDR_TOOLBAR_AREALIST            154
#define IDD_DIALOG_NPC                  155
#define ID_GRIDITEM_FULL_MODE           160
#define ID_GRIDITEM_DRAW_NORMAL         161
#define ID_GAME_PLAY                    162
#define IDR_TOOLBAR_BRUSHS              163
#define ID_TREE_OBJ_VIEW                164
#define IDB_BITMAP_BRUSH_ICONS          165
#define ID_GRIDITEM_LIGHTCOLOR          166
#define IDD_DIALOG_HEIGHTMAP            167
#define ID_GRIDITEM_CLEAR_COLOR         168
#define ID_GRIDITEM_LIGHT_RANGE         169
#define IDD_HELP_DIALOG_USE             180
#define IDR_MENU_MULTIOBJ               181
#define ID_GRIDITEM_LIGHT_ATT_C         182
#define ID_GRIDITEM_LIGHT_ATT_L         183
#define IDD_DIALOG_NEW_SCENE            184
#define ID_GRIDITEM_LIGHT_ATT_Q         185
#define IDD_DLG_NEW_BLOCK               186
#define ID_MAPLIST_OBJ_VIEW             187
#define IDR_TOOLBAR_SHOW                188
#define ID_GRIDITEM_DRAW_ATTR_WALK      189
#define ID_VIEW_PATHPOINT_LIST          190
#define ID_PATHPOINT_LIST_VIEW          191
#define IDR_TOOLBAR_PATHPOINTLIST       192
#define ID_TOOLBAR_PATHPOINT_ENABLE     193
#define ID_TOOLBAR_PATHPOINT_OPEN_FILE  194
#define ID_TOOLBAR_PATHPOINT_SAVE_FILE  195
#define IDC_LISTBOX_PATHPOINT           196
#define ID_GRIDITEM_DRAW_ATTR_FLY       200
#define IDR_TOOLBAR_MAP                 201
#define ID_GRIDITEM_DRAW_ATTR_DIG       202
#define ID_GRIDITEM_DRAW_HELPER         203
#define IDR_TOOLBAR_TERRAIN_FLAG        204
#define ID_GRIDITEM_OPTION_WATERCATOPTRICSKY 205
#define ID_GRIDITEM_FOG_ENABLE          206
#define IDD_DLG_BLOCK_INFO              207
#define ID_GRIDITEM_FOG_COLOR           208
#define IDD_DLG_GRASS                   208
#define IDR_MENU_BLOCK_OP               209
#define ID_GRIDITEM_FOG_MIN             220
#define ID_GRIDITEM_FOG_MAX             221
#define ID_GRIDITEM_ENV_SUN_COLOR       222
#define ID_GRIDITEM_ENV_SUN_SPECULAR    223
#define ID_GRIDITEM_ENV_TERRAIN_AMBIENT 224
#define ID_GRIDITEM_ENV_SUN_INCLINATION 225
#define ID_GRIDITEM_ENV_SUN_ROTATION    226
#define ID_GRIDITEM_OPTION_POSTPROCESS  227
#define ID_GRIDITEM_OPTION_POSTPROCESS_CONTRAST 228
#define ID_GRIDITEM_OPTION_POSTPROCESS_INTENSITY 229
#define ID_GRIDITEM_BACKMUSIC           240
#define ID_GRIDITEM_BACKMUSIC_START_TIME 241
#define ID_GRIDITEM_BACKMUSIC_DIFF_TIME 242
#define ID_GRIDITEM_BLOCK_FLAG_TEXTURE  243
#define ID_GRIDITEM_BLOCK_NAME          244
#define ID_GRIDITEM_BLOCK_FILENAME      245
#define ID_GRIDITEM_BLOCK_REGION_ID     246
#define IDC_RADIO_RECTANGLE             1000
#define IDC_RADIO_ROUNDED               1001
#define IDC_SLIDER_MIN                  1002
#define IDC_SLIDER_MAX                  1003
#define IDC_RADIO_BRUSH_VERTEX_DRAG     1004
#define IDC_RADIO_BRUSH_VERTEX_BRUSH    1005
#define IDC_RADIO_BRUSH_VERTEX_NOISE    1006
#define IDC_RADIO_BRUSH_VERTEX_SMOOTH   1007
#define IDC_RADIO_BRUSH_TERRAIN_VERTEX  1008
#define IDC_RADIO_BRUSH_TERRAIN_WALK    1009
#define IDC_HEIGHTMAP_IMG_RECT          1010
#define IDC_RADIO_BRUSH_TERRAIN_FLY     1010
#define IDC_RADIO_BRUSH_TERRAIN_DIG     1011
#define IDC_CHECK_SNAP_TO_GRID          1012
#define IDC_RADIO_BRUSH_TERRAIN_WATER   1013
#define IDC_RADIO_BRUSH_POINT_TILE      1014
#define IDC_RADIO_BRUSH_TILE_VERTEX     1015
#define IDC_CHECK_TILE                  1016
#define IDC_CHECK_TERRAIN               1017
#define IDC_COMBO_WATER                 1018
#define IDC_RADIO_BRUSH_VERTEX_DRAG2    1019
#define IDC_BLOCK_DRAW                  1022
#define IDC_BLOCK_DRAW_TEXT             1023
#define IDC_NEW_BLOCK_ATTRIB            1027
#define IDC_BUTTON2                     1030
#define IDC_BUTTON_GENERATE_ALL_MINIMAP 1031
#define IDC_BUTTON1                     1032
#define IDC_EDIT1                       1036
#define IDC_EDIT2                       1037
#define IDC_EDIT3                       1038
#define IDC_EDIT4                       1039
#define IDC_EDIT6                       1041
#define IDC_EDIT5                       1041
#define IDC_EDIT7                       1042
#define IDC_EDIT8                       1043
#define IDC_EDIT9                       1044
#define IDC_EDIT10                      1045
#define IDC_EDIT11                      1046
#define IDC_EDIT12                      1051
#define IDC_EDIT13                      1052
#define IDC_EDIT14                      1053
#define IDC_EDIT15                      1054
#define IDC_CHECK1                      1055
#define IDC_CHECK_FADEOUTIN             1055
#define IDC_SCROLLBAR3                  1060
#define IDC_SCROLLBAR4                  1061
#define IDC_BUTTON3                     1062
#define IDC_LIST1                       1064
#define IDC_LIST_GRASS                  1064
#define IDC_EDIT                        1068
#define IDC_SLIDER1                     1069
#define IDC_COMBO1                      1070
#define IDC_TEXT_WND                    1071
#define IDS_MULTIOBJECT_NEAR            32000
#define ID_BRUSH_MAP_FILTER_ALL         32772
#define ID_BRUSHMAP_2                   32774
#define ID_BRUSHMAP_4                   32776
#define ID_BRUSHMAP_3                   32777
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_MENU_THEMES_OFFICE2000       32785
#define ID_MENU_THEMES_OFFICEXP         32786
#define ID_MENU_THEMES_OFFICE2003       32787
#define ID_MENU_THEMES_OFFICEVISIO      32788
#define ID_GAME_HEIGHTMAP               32795
#define ID_GAME_SNAPSHOT                32797
#define ID_HELP_USE                     32799
#define ID_GAME_MOVEOBJECT              32800
#define ID_GAME_ADJUSTOBJECT            32801
#define ID_TOOL_TGA_REVERSE             32804
#define ID_GAME_NORMALIZABLE            32807
#define ID_TOOL_RECOMPUTE_OBJECT_LIGHT  32813
#define ID_TOOL_SAVE_ENV                32818
#define ID_TOOL_LOAD_ENV                32819
#define ID_TOOL_RECOMPUTE_OBJECT_BELONG 32822
#define ID_TOOL_CHECK_SAME_OBJECT       32825
#define ID_TOOL_DELETE_SAME_OBJECT      32826
#define ID_NEW_BLOCK                    32827
#define ID_BTN_SHOW_LINE                32839
#define ID_BTN_SHOW_NORMAL              32840
#define ID_BTN_SHOW_MASK_WALK           32841
#define ID_BTN_SHOW_MASK_FLY            32842
#define ID_BTN_SHOW_MASK_DIG            32843
#define ID_BTN_SHOW_HELPER              32844
#define ID_BTN_SHOW_FOG                 32845
#define ID_BTN_SHOW_MINIMAP             32846
#define ID_BTN_MAP_SLIDER               32848
#define ID_BTN_TERRAIN_SHOW             32849
#define ID_BTN_TERRAIN_WALK             32850
#define ID_BTN_EDIT_TERRAIN_WALK        32851
#define ID_BTN_EDIT_TERRAIN_SHOW        32852
#define ID_MENU_BO_PROPERTY             32857
#define ID_MENU_BO_MOVETO               32859
#define ID_MENU_THEMES_NATIVEOFFICE     32860
#define ID_MENU_BO_MINIMAP              32861
#define ID_BUTTON32862                  32862
#define ID_TOOLBAR_AREA_SHOW_ALL        32864
#define ID_MENU_AREA_ENABLE             32866
#define ID_32867                        32867
#define ID_TOOLBAR_AREA_ENABLE          32868
#define ID_TOOLBAR_AREA_SAVE_FILE       32869
#define ID_TOOLBAR_AREA_OPEN_FILE       32870
#define ID_TOOL_ADD_AREA_FROM_FILE      32872
#define ID_MENU_BO_DELETE               32874
#define ID_ENABLE_POSEEFFECT            32875
#define ID_OUTPUT_NPC_INFO              32879
#define ID_MENU_BO_COPY                 32883
#define ID_MENU_BO_POST                 32886
#define ID_32887                        32887
#define ID_COMPUTER_SM                  32888
#define ID_                             32889
#define ID_BUILD_SM                     32890
#define ID_BUILD_SM2                    32891
#define ID_PMODE                        32893
#define ID_32894                        32894
#define ID_VIEW_CENTER                  32895
#define ID_SHOWNORMAL                   32899
#define ID_ENABLEPOSEEFFECT             32905
#define ID_SAVEALL                      32906
#define ID_SAVECURRBLOCK                32907

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
